In [1]:
pip install pandas

Requirement already satisfied: pandas in /home/ubuntu/.local/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install backports.zoneinfo

:

In [3]:
pip install tzdata

Requirement already satisfied: tzdata in /home/ubuntu/.local/lib/python3.8/site-packages (2024.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import requests
import time
import datetime

import pytz
from datetime import datetime, timezone
from backports.zoneinfo import ZoneInfo



import psycopg2
import psycopg2.extras
from psycopg2.extensions import AsIs

from datetime import datetime, timezone

import dotenv
from dotenv import load_dotenv
import os

import warnings
warnings.filterwarnings("ignore")

In [5]:
def get_data():

    global data

    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = 'https://www.alphavantage.co/query?function=MARKET_STATUS&apikey=2M4KMLTI2FDMB6WB'
    r = requests.get(url)
    data = r.json()
    print(data)

    dataframe = pd.DataFrame.from_dict(data)
    market_values = dataframe[['markets']].values

            
    #Creating the dataframe
    cleaned_df = pd.DataFrame()
    temp_df = pd.DataFrame()
    for i in range(0,len(market_values),1):
        temp_df = pd.DataFrame(market_values[i][0], index=[i])
        if i == 0:
            cleaned_df = temp_df
        else:
            # print('in else')
            cleaned_df = pd.concat([cleaned_df,temp_df])


    return cleaned_df

In [6]:
dataframe = get_data()

{'endpoint': 'Global Market Open & Close Status', 'markets': [{'market_type': 'Equity', 'region': 'United States', 'primary_exchanges': 'NASDAQ, NYSE, AMEX, BATS', 'local_open': '09:30', 'local_close': '16:15', 'current_status': 'closed', 'notes': ''}, {'market_type': 'Equity', 'region': 'Canada', 'primary_exchanges': 'Toronto, Toronto Ventures', 'local_open': '09:30', 'local_close': '16:00', 'current_status': 'closed', 'notes': ''}, {'market_type': 'Equity', 'region': 'United Kingdom', 'primary_exchanges': 'London', 'local_open': '08:00', 'local_close': '16:30', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'Germany', 'primary_exchanges': 'XETRA, Berlin, Frankfurt, Munich, Stuttgart', 'local_open': '08:00', 'local_close': '20:00', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'France', 'primary_exchanges': 'Paris', 'local_open': '09:00', 'local_close': '17:30', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'Spain', 'primary_exchanges': 'Barcelona, Madrid', 'local_open': '09:00', 'local_close': '17:30', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'Portugal', 'primary_exchanges': 'Lisbon', 'local_open': '08:00', 'local_close': '16:30', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'Japan', 'primary_exchanges': 'Tokyo', 'local_open': '09:00', 'local_close': '15:00', 'current_status': 'closed', 'notes': 'Noon trading break from 11:30 to 12:30 local time'}, {'market_type': 'Equity', 'region': 'India', 'primary_exchanges': 'NSE, BSE', 'local_open': '09:15', 'local_close': '15:30', 'current_status': 'closed', 'notes': ''}, {'market_type': 'Equity', 'region': 'Mainland China', 'primary_exchanges': 'Shanghai, Shenzhen', 'local_open': '09:30', 'local_close': '15:00', 'current_status': 'closed', 'notes': 'Noon trading break from 11:30 to 13:00 local time'}, {'market_type': 'Equity', 'region': 'Hong Kong', 'primary_exchanges': 'Hong Kong', 'local_open': '09:30', 'local_close': '16:00', 'current_status': 'closed', 'notes': 'Noon trading break from 12:00 to 13:00 local time'}, {'market_type': 'Equity', 'region': 'Brazil', 'primary_exchanges': 'Sao Paolo', 'local_open': '10:00', 'local_close': '17:30', 'current_status': 'open', 'notes': ''}, {'market_type': 'Equity', 'region': 'Mexico', 'primary_exchanges': 'Mexico', 'local_open': '08:30', 'local_close': '15:00', 'current_status': 'closed', 'notes': ''}, {'market_type': 'Equity', 'region': 'South Africa', 'primary_exchanges': 'Johannesburg', 'local_open': '09:00', 'local_close': '17:00', 'current_status': 'open', 'notes': ''}, {'market_type': 'Forex', 'region': 'Global', 'primary_exchanges': 'Global', 'local_open': '00:00', 'local_close': '23:59', 'current_status': 'open', 'notes': 'The forex market is open 24 hours a day, EXCEPT between 16:00 EST on Friday and 17:00 EST on Sunday'}, {'market_type': 'Cryptocurrency', 'region': 'Global', 'primary_exchanges': 'Global', 'local_open': '00:00', 'local_close': '23:59', 'current_status': 'open', 'notes': 'The cryptocurrency market is open 24 hours a day'}]}

In [7]:
check_date = datetime.now(timezone.utc)

# This was teh code generated to save teh raw data obtained from the API. It is not in use for now as 
# the cleaned_df ddataframe is in globval state and can be called by any function. So SKIP THIS CODE PEICE. 


# hostname ="database-1.ctzm0hf7fhri.eu-central-1.rds.amazonaws.com" 
# database="dyDATA_new" 
# username='postgres'
# pwd='Proc2023awsrdspostgresql'
# port_id=5432

# table_name = '"dyTRADE".'
# column_name = '''("financial_market_PK",
# "financial_market_date",
# "financial_market_UUID",
# "financial_market_financial_market_PK",
# financial_market_region,
# "financial_market_primary_exchange",
# financial_market_local_open,
# financial_market_local_close,
# financial_market_notes)'''


# try:
#     with psycopg2.connect(host=hostname,dbname=database,user=username,password=pwd,port=port_id) as conn:
#         with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
#             cur.execute(f'''SELECT * FROM "dyTRADE".{table_name} where date = {check_date}''')
#             result = cur.fetchall()
#             print("Query executed successfully.")
# except:
#     raise Exception("The query was not able to write into the financial market, please verify")

# if result == None:
#     data = get_data()
#     try:
#         with psycopg2.connect(host=hostname,dbname=database,user=username,password=pwd,port=port_id) as conn:
#             with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
#                 table_column=table_name+column_name
#                 cur.execute("INSERT INTO "+table_column+" VALUES " + (cleaned_df['index'], ))
#     except:
#         raise Exception("The query was not able to write into the financial market, please verify")
#     # print("Unable to obtain data from API")
# else:

In [8]:
# def get_data(time_delay_minutes):
#     seconds =  time_delay_minutes * 60
#     while seconds > 0:
    
#         # Timer represents time left on countdown
#         timer = datetime.timedelta(seconds = seconds)

#         # Prints the time left on the timer
#         print(timer, end="\r")
#         time.sleep(1)
#         seconds -= 1
#     meta_data = get_meta_data()
#     print(meta_data)

In [11]:
cleaned_df = dataframe.copy()

In [12]:
cleaned_df

,market_type,region,primary_exchanges,local_open,local_close,current_status,notes
0,Equity,United States,"NASDAQ, NYSE, AMEX, BATS",09:30,16:15,closed,
1,Equity,Canada,"Toronto, Toronto Ventures",09:30,16:00,closed,
2,Equity,United Kingdom,London,08:00,16:30,open,
3,Equity,Germany,"XETRA, Berlin, Frankfurt, Munich, Stuttgart",08:00,20:00,open,
4,Equity,France,Paris,09:00,17:30,open,
5,Equity,Spain,"Barcelona, Madrid",09:00,17:30,open,
6,Equity,Portugal,Lisbon,08:00,16:30,open,
7,Equity,Japan,Tokyo,09:00,15:00,closed,Noon trading break from 11:30 to 12:30 local time
8,Equity,India,"NSE, BSE",09:15,15:30,closed,
9,Equity,Mainland China,"Shanghai, Shenzhen",09:30,15:00,closed,Noon trading break from 11:30 to 13:00 local time
10,Equity,Hong Kong,Hong Kong,09:30,16:00,closed,Noon trading break from 12:00 to 13:00 local time
11,Equity,Brazil,Sao Paolo,10:00,17:30,open,
12,Equity,Mexico,Mexico,08:30,15:00,closed,
13,Equity,South Africa,Johannesburg,09:00,17:00,open,
14,Forex,Global,Global,00:00,23:59,open,"The forex market is open 24 hours a day, EXCEP..."
15,Cryptocurrency,Global,Global,00:00,23:59,open,The cryptocurrency market is open 24 hours a day

In [9]:
from datetime import date

In [12]:
######################################################################
# THIS JUPYTER CELL IS FOR TESTING ONLY 1 ROW. 
######################################################################

# load_dotenv("/home/ubuntu/FMU_Bot/Credentials.env")
# hostname, port_id, database, username, password = (
#     os.getenv(key) for key in ["DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD"]
# )

hostname ="database-1.ctzm0hf7fhri.eu-central-1.rds.amazonaws.com" 
database="dyDATA_new" 
username='postgres'
password='Proc2023awsrdspostgresql'
port_id=5432

cleaned_df['local_open'] = pd.to_datetime(cleaned_df['local_open'])#, format='%Y-%m-%d %H:%M:%S') #line 17
cleaned_df['local_close'] = pd.to_datetime(cleaned_df['local_close'])#, format='%y-%m-%d %H:%M:%S')
print(cleaned_df['local_open'])
# cleaned_df['primary_exchanges'] = cleaned_df['primary_exchanges'].apply(lambda x: [item[1:-1] for sublist in x for item in sublist] if isinstance(x, list) else x)

#Separate the stock markets, as they are clubbed by country
for i in range(len(cleaned_df)):
    # if cleaned_df['primary_exchanges'][i].find(',') == 0:
    cleaned_df['primary_exchanges'][i] = cleaned_df['primary_exchanges'][i].split(',')
cleaned_df = cleaned_df.explode(column = 'primary_exchanges', ignore_index=True)
# Removing whitespaces from starting and ending of the cells
cleaned_df['primary_exchanges'] = cleaned_df['primary_exchanges'].apply(lambda x: x.strip())

cleaned_df['financial_market_PK'] = ""
cleaned_df['financial_market_ID'] = ""
cleaned_df['financial_market_timezone_region_city_PK'] = ""
with psycopg2.connect(host=hostname,dbname=database,user=username,password=password,port=port_id) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            market = cleaned_df['primary_exchanges'][0]
            print(f"now we in: {market}")
            financial_market_PK= '''"financial_market_PK"'''
            financial_market_ID= '''"financial_market_ID"'''
            financial_market_name= '''"financial_market_name"'''
            financial_market_timezone_region_city_PK = '''"financial_market_timezone_region_city_PK"'''

            ################################################
            query=f'''SELECT {financial_market_PK},{financial_market_ID},{financial_market_name},{financial_market_timezone_region_city_PK} 
            from "dyLEARN".financial_market_list_view 
            where financial_market_code='{market}' or 
            financial_market_name='{market}' or 
            financial_market_alphavantage_name='{market}'; '''
            print(query)
            cur.execute(query)
            result = cur.fetchall()
            print(result)


PK=result[0][0]
print(PK)
ID=result[0][1]
timezone_region_city_PK = result[0][3]
print(timezone_region_city_PK)

cleaned_df['financial_market_PK'][0] = PK
cleaned_df['financial_market_ID'][0] = ID
cleaned_df['financial_market_timezone_region_city_PK'][0] = timezone_region_city_PK

with psycopg2.connect(host=hostname,dbname=database,user=username,password=password,port=port_id) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            print(f"now we in: {market}")
            country_timezone_region_city_name = '''"timezone_region_city_name"'''
            country_timezone_region_city_PK = '''"timezone_region_city_region_city_PK"'''
            query=f'''SELECT {country_timezone_region_city_name} 
            from "dyGEO".country_timezone_region_city_rel_view
            where {country_timezone_region_city_PK}='{timezone_region_city_PK}'; '''
            print(query)
            cur.execute(query)
            result = cur.fetchall()
            print(result[0])
            country_zone = str(result[0][0])
            res = country_zone.split("-", 1)
            zone = res[1]
            # zone = zone.rstrip("ca-")
            print('printing zone:', zone)
                 

time_cols = list(cleaned_df.columns[cleaned_df.columns.str.contains(pat = 'local')])
for col in time_cols:
    # print("LocaL OPEN time:", cleaned_df['local_open'][i], "Market name:", cleaned_df['primary_exchanges'][i])
    local  = str(cleaned_df[col][0])
    print (local)
    # Get timezone we're trying to convert from
    local_tz = ZoneInfo(zone)
    # UTC timezone
    utc_tz = ZoneInfo("UTC")

    # print((local_open))

    dt = datetime.strptime(local,"%Y-%m-%d %H:%M:%S")
    dt = dt.replace(tzinfo=local_tz)
    dt_open_utc = dt.astimezone(utc_tz)
    dt_open_utc = pd.Timestamp(dt_open_utc)
    cleaned_df[col][0] = dt_open_utc.tz_convert('utc')

0    2024-06-22 09:30:00
1    2024-06-22 09:30:00
2    2024-06-22 08:00:00
3    2024-06-22 08:00:00
4    2024-06-22 09:00:00
5    2024-06-22 09:00:00
6    2024-06-22 08:00:00
7    2024-06-22 09:00:00
8    2024-06-22 09:15:00
9    2024-06-22 09:30:00
10   2024-06-22 09:30:00
11   2024-06-22 10:00:00
12   2024-06-22 08:30:00
13   2024-06-22 09:00:00
14   2024-06-22 00:00:00
15   2024-06-22 00:00:00
Name: local_open, dtype: datetime64[ns]
now we in: NASDAQ
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
            from "dyLEARN".financial_market_list_view
            where financial_market_code='NASDAQ' or
            financial_market_name='NASDAQ' or
            financial_market_alphavantage_name='NASDAQ';
[[16, None, 'NASDAQ', 16]]
16
16
now we in: NASDAQ
SELECT "timezone_region_city_name"
            from "dyGEO".country_timezone_region_city_rel_view
            where "timezone_region_city_region_city_PK"='16';

UndefinedColumn: column "timezone_region_city_name" does not exist
LINE 1: SELECT "timezone_region_city_name"
               ^

In [32]:
cleaned_df = dataframe.copy()

In [33]:
def correct_date_time(cleaned_df):

    # Get region data from table
    cwd = os.getcwd()
    file_path = os.path.join(cwd, "Credentials.env")
    load_dotenv(file_path)
    hostname, port_id, database, username, password = (
        os.getenv(key) for key in ["DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD"]
    )
    print(hostname, port_id, database, username, password)

    # hostname ="database-1.ctzm0hf7fhri.eu-central-1.rds.amazonaws.com" 
    # database="dyDATA_new" 
    # username='postgres'
    # password='Proc2023awsrdspostgresql'
    # port_id=5432

    ###################
    # Changing the time only values into datetime
    #this part need to be fixed!!! The fix is not to uncomment the format line, it is just there was future purposes.
    cleaned_df['local_open'] = pd.to_datetime(cleaned_df['local_open'])#, format='%Y-%m-%d %H:%M:%S') #line 17
    cleaned_df['local_close'] = pd.to_datetime(cleaned_df['local_close'])#, format='%y-%m-%d %H:%M:%S')
    print(cleaned_df['local_open'])

    #Separate the stock markets, as they are clubbed by country
    cleaned_df['primary_exchanges'] = cleaned_df['primary_exchanges'].apply(lambda x: [item[1:-1] for sublist in x for item in sublist] if isinstance(x, list) else x)
    # print(cleaned_df['primary_exchanges'])
    for i in range(len(cleaned_df)):
        # if cleaned_df['primary_exchanges'][i].find(',') == 0:
        cleaned_df['primary_exchanges'][i] = cleaned_df['primary_exchanges'][i].split(',')
    cleaned_df = cleaned_df.explode(column = 'primary_exchanges', ignore_index=True)
    # Removing whitespaces from starting and ending of the cells
    cleaned_df['primary_exchanges'] = cleaned_df['primary_exchanges'].apply(lambda x: x.strip())

    # FIILING TIME RELATRED COLUMNS IN A LIST
    time_cols = list(cleaned_df.columns[cleaned_df.columns.str.contains(pat = 'local')])

    cleaned_df['financial_market_PK'] = ""
    cleaned_df['financial_market_ID'] = ""
    cleaned_df['financial_market_timezone_region_city_PK'] = ""
    missing_market_list = []
    for i in range(len(cleaned_df)):
        #Adding neccessary columns to the dataframe like PK and ID
        with psycopg2.connect(host=hostname,dbname=database,user=username,password=password,port=port_id) as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                market = cleaned_df['primary_exchanges'][i]
                print(f"now we in: {market}")
                financial_market_PK= '''"financial_market_PK"'''
                financial_market_ID= '''"financial_market_ID"'''
                financial_market_name= '''"financial_market_name"'''
                financial_market_timezone_region_city_PK = '''"financial_market_timezone_region_city_PK"'''

                ################################################
                query=f'''SELECT {financial_market_PK},{financial_market_ID},{financial_market_name},{financial_market_timezone_region_city_PK} 
                from "dyLEARN".financial_market_list_view 
                where financial_market_code='{market}' or 
                financial_market_name='{market}' or 
                financial_market_alphavantage_name='{market}'; '''
                print(query)
                cur.execute(query)
                result = cur.fetchall()
                print(result)
                
                # cleaned_df['financial_market_timezone_region_city_PK'] = result[2]
                for row in result:
                    PK=row[0]
                    ID=row[1]
                    timezone_region_city_PK = row[3]
                    print(PK)
            

                cleaned_df['financial_market_PK'][i] = PK
                cleaned_df['financial_market_ID'][i] = ID
                cleaned_df['financial_market_timezone_region_city_PK'][i] = timezone_region_city_PK
                # cleaned_df['financial_market_PK'][i] = result[0]
                # cleaned_df['financial_market_ID'][i] = result[1]
                if timezone_region_city_PK == None:
                    missing_market_list.append(market)
                    print("Continuing")
                    if cleaned_df['region'][i] == 'Global':
                        cleaned_df['notes'][i]=("This market is global")
                    else:
                        cleaned_df['notes'][i]=("Error fetching the timezone_ID")
                    continue
                    continue

        with psycopg2.connect(host=hostname,dbname=database,user=username,password=password,port=port_id) as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                country_timezone_region_city_name = '''"timezone_region_city_name"'''
                country_timezone_region_city_PK = '''"timezone_region_city_PK"'''
                query=f'''SELECT {country_timezone_region_city_name} 
                from "dyGEO".timezone_region_city_list
                where {country_timezone_region_city_PK}='{timezone_region_city_PK}'; '''
                print(query)
                cur.execute(query)
                result = cur.fetchall()
                print(result[0])
                # country_zone = str(result[0][0])
                # res = country_zone.split("-", 1)
                zone = result[0][0] #res[1]


        
        
        print("now to convert the timezone")
        # Time correction to UTC
        for col in time_cols:
            # print("LocaL OPEN time:", cleaned_df['local_open'][i], "Market name:", cleaned_df['primary_exchanges'][i])
            local  = str(cleaned_df[col][i])
            print ("Got local time: ", local)
            # Get timezone we're trying to convert from
            local_tz = ZoneInfo(zone)
            # UTC timezone
            utc_tz = ZoneInfo("UTC")

            # print((local_open))

            dt = datetime.strptime(local,"%Y-%m-%d %H:%M:%S")
            dt = dt.replace(tzinfo=local_tz)
            dt_open_utc = dt.astimezone(utc_tz)
            dt_open_utc = pd.Timestamp(dt_open_utc)
            cleaned_df[col][i] = dt_open_utc.tz_convert('utc')
            print("Zone: ", zone, "Converted to UTC: ", cleaned_df[col][i])
            # print("UTC time:", cleaned_df['local_open'][i], "Market name:", cleaned_df['primary_exchanges'][i])

        # #Removing timezones
        # cleaned_df['local_open'] = cleaned_df['local_open'][i].replace(tzinfo=None)
        # cleaned_df['local_close'] = cleaned_df['local_close'][i].replace(tzinfo=None)

    print(cleaned_df)

    print("Missing market List:", missing_market_list)

    return (cleaned_df)

In [34]:
time_adjusted_dataframe = correct_date_time(cleaned_df)

database-1.ctzm0hf7fhri.eu-central-1.rds.amazonaws.com 5432 dyDATA_new postgres Proc2023awsrdspostgresql
0    2024-06-24 09:30:00
1    2024-06-24 09:30:00
2    2024-06-24 08:00:00
3    2024-06-24 08:00:00
4    2024-06-24 09:00:00
5    2024-06-24 09:00:00
6    2024-06-24 08:00:00
7    2024-06-24 09:00:00
8    2024-06-24 09:15:00
9    2024-06-24 09:30:00
10   2024-06-24 09:30:00
11   2024-06-24 10:00:00
12   2024-06-24 08:30:00
13   2024-06-24 09:00:00
14   2024-06-24 00:00:00
15   2024-06-24 00:00:00
Name: local_open, dtype: datetime64[ns]
now we in: NASDAQ
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='NASDAQ' or
                financial_market_name='NASDAQ' or
                financial_market_alphavantage_name='NASDAQ';
[[16, None, 'NASDAQ', 16]]
16
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='16';
['America/New_York']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  America/New_York Converted to UTC:  2024-06-24 13:30:00+00:00
Got local time:  2024-06-24 16:15:00
Zone:  America/New_York Converted to UTC:  2024-06-24 20:15:00+00:00
now we in: NYSE
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='NYSE' or
                financial_market_name='NYSE' or
                financial_market_alphavantage_name='NYSE';
[[20, None, 'New York Stock Exchange', 16]]
20

SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='16';
['America/New_York']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  America/New_York Converted to UTC:  2024-06-24 13:30:00+00:00
Got local time:  2024-06-24 16:15:00
Zone:  America/New_York Converted to UTC:  2024-06-24 20:15:00+00:00
now we in: AMEX
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='AMEX' or
                financial_market_name='AMEX' or
                financial_market_alphavantage_name='AMEX';
[[40, None, 'American Stock Exchange', 16]]
40
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='16';
['America/New_York']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  America/New_York Converted to UTC:  2024-06-24 13:30:00+00:00
Got local time:  2024-06-24 16:15:00
Zone:  America/New_York Converted to UTC:  2024-06-24 20:15:00+00:00
now we in: BATS
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='BATS' or
                financial_market_name='BATS' or
                financial_market_alphavantage_name='BATS';
[[41, None, 'Better Alternative Trading System', 38]]
41
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='38';
['Europe/London']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  Europe/London Converted to UTC:  2024-06-24 08:30:00+00:00
Got local time:  2024-06-24 16:15:00
Zone:  Europe/London Converted to UTC:  2024-06-24 15:15:00+00:00
now we in: Toronto
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Toronto' or
                financial_market_name='Toronto' or
                financial_market_alphavantage_name='Toronto';
[[31, None, 'Toronto Stock Exchange', 106]]
31
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='106';
['America/Toronto']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  America/Toronto Converted to UTC:  2024-06-24 13:30:00+00:00
Got local time:  2024-06-24 16:00:00
Zone:  America/Toronto Converted to UTC:  2024-06-24 20:00:00+00:00
now we in: Toronto Ventures
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Toronto Ventures' or
                financial_market_name='Toronto Ventures' or
                financial_market_alphavantage_name='Toronto Ventures';
[[32, None, 'TSX Venture Exchange', 106]]
32
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='106';
['America/Toronto']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  America/Toronto Converted to UTC:  2024-06-24 13:30:00+00:00
Got local time:  2024-06-24 16:00:00
Zone:  America/Toronto Converted to UTC:  2024-06-24 20:00:00+00:00
now we in: London
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='London' or
                financial_market_name='London' or
                financial_market_alphavantage_name='London';
[[13, None, 'London Stock Exchange', 38]]
13
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='38';
['Europe/London']
now to convert the timezone
Got local time:  2024-06-24 08:00:00
Zone:  Europe/London Converted to UTC:  2024-06-24 07:00:00+00:00
Got local time:  2024-06-24 16:30:00
Zone:  Europe/London Converted to UTC:  2024-06-24 15:30:00+00:00
now we in: XETRA
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='XETRA' or
                financial_market_name='XETRA' or
                financial_market_alphavantage_name='XETRA';
[[8, None, 'Deutsche Börse (XETRA)', 109]]
8
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='109';
['Europe/Berlin']
now to convert the timezone
Got local time:  2024-06-24 08:00:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 06:00:00+00:00
Got local time:  2024-06-24 20:00:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 18:00:00+00:00
now we in: Berlin
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Berlin' or
                financial_market_name='Berlin' or
                financial_market_alphavantage_name='Berlin';
[[42, None, 'Berlin Stock Exchange', 109]]
42
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='109';
['Europe/Berlin']
now to convert the timezone
Got local time:  2024-06-24 08:00:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 06:00:00+00:00
Got local time:  2024-06-24 20:00:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 18:00:00+00:00
now we in: Frankfurt
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Frankfurt' or
                financial_market_name='Frankfurt' or
                financial_market_alphavantage_name='Frankfurt';
[[44, None, 'Frankfurt Stock Exchange', None]]
44
Continuing
now we in: Munich
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Munich' or
                financial_market_name='Munich' or
                financial_market_alphavantage_name='Munich';
[[43, None, 'Munich Stock Exchange', None]]
43
Continuing
now we in: Stuttgart
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Stuttgart' or
                financial_market_name='Stuttgart' or
                financial_market_alphavantage_name='Stuttgart';
[[45, None, 'Stuttgart Stock Exchange', None]]
45
Continuing
now we in: Paris
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Paris' or
                financial_market_name='Paris' or
                financial_market_alphavantage_name='Paris';
[[24, None, 'NYSE Euronext Paris', 117], [37, 37, 'Paris Stock Market - Euronext', 117]]
24
37
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='117';
['Europe/Paris']
now to convert the timezone
Got local time:  2024-06-24 09:00:00
Zone:  Europe/Paris Converted to UTC:  2024-06-24 07:00:00+00:00
Got local time:  2024-06-24 17:30:00
Zone:  Europe/Paris Converted to UTC:  2024-06-24 15:30:00+00:00
now we in: Barcelona
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Barcelona' or
                financial_market_name='Barcelona' or
                financial_market_alphavantage_name='Barcelona';
[[46, None, 'Barcelona Stock Exchange', None]]
46
Continuing
now we in: Madrid
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Madrid' or
                financial_market_name='Madrid' or
                financial_market_alphavantage_name='Madrid';
[[47, None, 'Madrid Stock Exchange', 109]]
47
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='109';
['Europe/Berlin']
now to convert the timezone
Got local time:  2024-06-24 09:00:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 07:00:00+00:00
Got local time:  2024-06-24 17:30:00
Zone:  Europe/Berlin Converted to UTC:  2024-06-24 15:30:00+00:00
now we in: Lisbon
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Lisbon' or
                financial_market_name='Lisbon' or
                financial_market_alphavantage_name='Lisbon';
[[23, None, 'NYSE Euronext Lisbon', 116], [48, None, 'Euronext Lisbon Stock Exchange', 116]]
23
48
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='116';
['Europe/Lisbon']
now to convert the timezone
Got local time:  2024-06-24 08:00:00
Zone:  Europe/Lisbon Converted to UTC:  2024-06-24 07:00:00+00:00
Got local time:  2024-06-24 16:30:00
Zone:  Europe/Lisbon Converted to UTC:  2024-06-24 15:30:00+00:00
now we in: Tokyo
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Tokyo' or
                financial_market_name='Tokyo' or
                financial_market_alphavantage_name='Tokyo';
[[30, None, 'Tokyo Stock Exchange', 89]]
30
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='89';
['Asia/Tokyo']
now to convert the timezone
Got local time:  2024-06-24 09:00:00
Zone:  Asia/Tokyo Converted to UTC:  2024-06-24 00:00:00+00:00
Got local time:  2024-06-24 15:00:00
Zone:  Asia/Tokyo Converted to UTC:  2024-06-24 06:00:00+00:00
now we in: NSE
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='NSE' or
                financial_market_name='NSE' or
                financial_market_alphavantage_name='NSE';
[[49, None, 'National Stock Exchange of India', 74]]
49
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='74';
['Asia/Kolkata']
now to convert the timezone
Got local time:  2024-06-24 09:15:00
Zone:  Asia/Kolkata Converted to UTC:  2024-06-24 03:45:00+00:00
Got local time:  2024-06-24 15:30:00
Zone:  Asia/Kolkata Converted to UTC:  2024-06-24 10:00:00+00:00
now we in: BSE
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='BSE' or
                financial_market_name='BSE' or
                financial_market_alphavantage_name='BSE';
[]
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='74';
['Asia/Kolkata']
now to convert the timezone
Got local time:  2024-06-24 09:15:00
Zone:  Asia/Kolkata Converted to UTC:  2024-06-24 03:45:00+00:00
Got local time:  2024-06-24 15:30:00
Zone:  Asia/Kolkata Converted to UTC:  2024-06-24 10:00:00+00:00
now we in: Shanghai
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Shanghai' or
                financial_market_name='Shanghai' or
                financial_market_alphavantage_name='Shanghai';
[[27, None, 'Shangai Stock Exchange', 120]]
27
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='120';
['Asia/Shanghai']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  Asia/Shanghai Converted to UTC:  2024-06-24 01:30:00+00:00
Got local time:  2024-06-24 15:00:00
Zone:  Asia/Shanghai Converted to UTC:  2024-06-24 07:00:00+00:00
now we in: Shenzhen
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Shenzhen' or
                financial_market_name='Shenzhen' or
                financial_market_alphavantage_name='Shenzhen';
[]
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='120';
['Asia/Shanghai']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  Asia/Shanghai Converted to UTC:  2024-06-24 01:30:00+00:00
Got local time:  2024-06-24 15:00:00
Zone:  Asia/Shanghai Converted to UTC:  2024-06-24 07:00:00+00:00
now we in: Hong Kong
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Hong Kong' or
                financial_market_name='Hong Kong' or
                financial_market_alphavantage_name='Hong Kong';
[[10, None, 'Hong Kong Exchanges', 110]]
10
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='110';
['Asia/Hong_Kong']
now to convert the timezone
Got local time:  2024-06-24 09:30:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 01:30:00+00:00
Got local time:  2024-06-24 16:00:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 08:00:00+00:00
now we in: Sao Paolo
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Sao Paolo' or
                financial_market_name='Sao Paolo' or
                financial_market_alphavantage_name='Sao Paolo';
[]
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='110';
['Asia/Hong_Kong']
now to convert the timezone
Got local time:  2024-06-24 10:00:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 02:00:00+00:00
Got local time:  2024-06-24 17:30:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 09:30:00+00:00
now we in: Mexico
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Mexico' or
                financial_market_name='Mexico' or
                financial_market_alphavantage_name='Mexico';
[]
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='110';
['Asia/Hong_Kong']
now to convert the timezone
Got local time:  2024-06-24 08:30:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 00:30:00+00:00
Got local time:  2024-06-24 15:00:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 07:00:00+00:00
now we in: Johannesburg
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Johannesburg' or
                financial_market_name='Johannesburg' or
                financial_market_alphavantage_name='Johannesburg';
[]
SELECT "timezone_region_city_name"
                from "dyGEO".timezone_region_city_list
                where "timezone_region_city_PK"='110';
['Asia/Hong_Kong']
now to convert the timezone
Got local time:  2024-06-24 09:00:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 01:00:00+00:00
Got local time:  2024-06-24 17:00:00
Zone:  Asia/Hong_Kong Converted to UTC:  2024-06-24 09:00:00+00:00
now we in: Global
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Global' or
                financial_market_name='Global' or
                financial_market_alphavantage_name='Global';
[[35, None, 'Foreign Exchange', None]]
35
Continuing
now we in: Global
SELECT "financial_market_PK","financial_market_ID","financial_market_name","financial_market_timezone_region_city_PK"
                from "dyLEARN".financial_market_list_view
                where financial_market_code='Global' or
                financial_market_name='Global' or
                financial_market_alphavantage_name='Global';
[[35, None, 'Foreign Exchange', None]]
35
Continuing
       market_type          region primary_exchanges  \
0           Equity   United States            NASDAQ
1           Equity   United States              NYSE
2           Equity   United States              AMEX
3           Equity   United States              BATS
4           Equity          Canada           Toronto
5           Equity          Canada  Toronto Ventures
6           Equity  United Kingdom            London
7           Equity         Germany             XETRA
8           Equity         Germany            Berlin
9           Equity         Germany         Frankfurt
10          Equity         Germany            Munich
11          Equity         Germany         Stuttgart
12          Equity          France             Paris
13          Equity           Spain         Barcelona
14          Equity           Spain            Madrid
15          Equity        Portugal            Lisbon
16          Equity           Japan             Tokyo
17          Equity           India               NSE
18          Equity           India               BSE
19          Equity  Mainland China          Shanghai
20          Equity  Mainland China          Shenzhen
21          Equity       Hong Kong         Hong Kong
22          Equity          Brazil         Sao Paolo
23          Equity          Mexico            Mexico
24          Equity    South Africa      Johannesburg
25           Forex          Global            Global
26  Cryptocurrency          Global            Global

                   local_open                local_close current_status  \
0   2024-06-24 13:30:00+00:00  2024-06-24 20:15:00+00:00         closed
1   2024-06-24 13:30:00+00:00  2024-06-24 20:15:00+00:00         closed
2   2024-06-24 13:30:00+00:00  2024-06-24 20:15:00+00:00         closed

In [35]:
this_day = str(date.today())

In [36]:
for i in range(len(time_adjusted_dataframe)):
    if time_adjusted_dataframe['notes'][i] == "":
        print("In here")
        time_adjusted_dataframe['notes'][i] = "-"

In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here
In here

In [37]:
time_adjusted_dataframe

,market_type,region,primary_exchanges,local_open,local_close,current_status,notes,financial_market_PK,financial_market_ID,financial_market_timezone_region_city_PK
0,Equity,United States,NASDAQ,2024-06-24 13:30:00+00:00,2024-06-24 20:15:00+00:00,closed,-,16,None,16
1,Equity,United States,NYSE,2024-06-24 13:30:00+00:00,2024-06-24 20:15:00+00:00,closed,-,20,None,16
2,Equity,United States,AMEX,2024-06-24 13:30:00+00:00,2024-06-24 20:15:00+00:00,closed,-,40,None,16
3,Equity,United States,BATS,2024-06-24 08:30:00+00:00,2024-06-24 15:15:00+00:00,closed,-,41,None,38
4,Equity,Canada,Toronto,2024-06-24 13:30:00+00:00,2024-06-24 20:00:00+00:00,closed,-,31,None,106
5,Equity,Canada,Toronto Ventures,2024-06-24 13:30:00+00:00,2024-06-24 20:00:00+00:00,closed,-,32,None,106
6,Equity,United Kingdom,London,2024-06-24 07:00:00+00:00,2024-06-24 15:30:00+00:00,open,-,13,None,38
7,Equity,Germany,XETRA,2024-06-24 06:00:00+00:00,2024-06-24 18:00:00+00:00,open,-,8,None,109
8,Equity,Germany,Berlin,2024-06-24 06:00:00+00:00,2024-06-24 18:00:00+00:00,open,-,42,None,109
9,Equity,Germany,Frankfurt,2024-06-24 08:00:00,2024-06-24 20:00:00,open,Error fetching the timezone_ID,44,None,None
10,Equity,Germany,Munich,2024-06-24 08:00:00,2024-06-24 20:00:00,open,Error fetching the timezone_ID,43,None,None
11,Equity,Germany,Stuttgart,2024-06-24 08:00:00,2024-06-24 20:00:00,open,Error fetching the timezone_ID,45,None,None
12,Equity,France,Paris,2024-06-24 07:00:00+00:00,2024-06-24 15:30:00+00:00,open,-,37,37,117
13,Equity,Spain,Barcelona,2024-06-24 09:00:00,2024-06-24 17:30:00,open,Error fetching the timezone_ID,46,None,None
14,Equity,Spain,Madrid,2024-06-24 07:00:00+00:00,2024-06-24 15:30:00+00:00,open,-,47,None,109
15,Equity,Portugal,Lisbon,2024-06-24 07:00:00+00:00,2024-06-24 15:30:00+00:00,open,-,48,None,116
16,Equity,Japan,Tokyo,2024-06-24 00:00:00+00:00,2024-06-24 06:00:00+00:00,closed,Noon trading break from 11:30 to 12:30 local time,30,None,89
17,Equity,India,NSE,2024-06-24 03:45:00+00:00,2024-06-24 10:00:00+00:00,closed,-,49,None,74
18,Equity,India,BSE,2024-06-24 03:45:00+00:00,2024-06-24 10:00:00+00:00,closed,-,49,None,74
19,Equity,Mainland China,Shanghai,2024-06-24 01:30:00+00:00,2024-06-24 07:00:00+00:00,closed,Noon trading break from 11:30 to 13:00 local time,27,None,120
20,Equity,Mainland China,Shenzhen,2024-06-24 01:30:00+00:00,2024-06-24 07:00:00+00:00,closed,Noon trading break from 11:30 to 13:00 local time,27,None,120
21,Equity,Hong Kong,Hong Kong,2024-06-24 01:30:00+00:00,2024-06-24 08:00:00+00:00,closed,Noon trading break from 12:00 to 13:00 local time,10,None,110
22,Equity,Brazil,Sao Paolo,2024-06-24 02:00:00+00:00,2024-06-24 09:30:00+00:00,open,-,10,None,110
23,Equity,Mexico,Mexico,2024-06-24 00:30:00+00:00,2024-06-24 07:00:00+00:00,closed,-,10,None,110
24,Equity,South Africa,Johannesburg,2024-06-24 01:00:00+00:00,2024-06-24 09:00:00+00:00,open,-,10,None,110
25,Forex,Global,Global,2024-06-24 00:00:00,2024-06-24 23:59:00,open,This market is global,35,None,None
26,Cryptocurrency,Global,Global,2024-06-24 00:00:00,2024-06-24 23:59:00,open,This market is global,35,None,None

In [38]:
cwd = os.getcwd()
file_path = os.path.join(cwd, "Credentials.env")
load_dotenv(file_path)
hostname, port_id, database, username, password = (
    os.getenv(key) for key in ["DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD"]
)
print(hostname, port_id, database, username, password)

# "financial_market_opening_status_UUID"

table_name = '''"dyTRADE".financial_market_session_time_log'''

#Commenting for time till market_PK not ready time_adjusted_dataframe['financial_market_PK'][i],

try:
    with psycopg2.connect(host=hostname,dbname=database,user=username,password=password,port=port_id) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            for i in range(len(time_adjusted_dataframe)):
                if time_adjusted_dataframe['current_status'][i] =="closed":
                    time_adjusted_dataframe['current_status'][i]=0
                else:
                    time_adjusted_dataframe['current_status'][i]=1
                if time_adjusted_dataframe['notes'][i] is None:
                    time_adjusted_dataframe['notes'][i] = " "
                ################################################
                id= '''"financial_market_session_time_ID"'''
                financial_market_PK= '''"financial_market_session_time_financial_market_PK"'''
                session_time_log_utc_date= '''"financial_market_session_time_log_utc_date"'''
                opening_UTC_time= '''"financial_market_session_time_opening_UTC_time"'''
                closure_UTC_time= '''"financial_market_session_time_closure_UTC_time"'''
                session_time_note= '''"financial_market_session_time_note"'''
                market_status= '''"financial_market_session_time_activity_status"'''
                market_session_PK =  '''"financial_market_session_time_market_session_PK"'''
                
                query=f'''INSERT INTO {table_name} ({id},{financial_market_PK},{market_session_PK},{session_time_log_utc_date},{opening_UTC_time},{closure_UTC_time},{session_time_note},{market_status})
                VALUES ({time_adjusted_dataframe['financial_market_PK'][i]},{time_adjusted_dataframe['financial_market_PK'][i]},2,'{this_day}','{time_adjusted_dataframe['local_open'][i]}','{time_adjusted_dataframe['local_close'][i]}',
                '{time_adjusted_dataframe['notes'][i]}',{time_adjusted_dataframe['current_status'][i]})'''
                print(query)
                cur.execute(query)
except:
    raise Exception("The query was not able to write into the financial")

INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (16,16,1,'2024-06-24','2024-06-24 13:30:00+00:00','2024-06-24 20:15:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (20,20,1,'2024-06-24','2024-06-24 13:30:00+00:00','2024-06-24 20:15:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (40,40,1,'2024-06-24','2024-06-24 13:30:00+00:00','2024-06-24 20:15:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (41,41,1,'2024-06-24','2024-06-24 08:30:00+00:00','2024-06-24 15:15:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (31,31,1,'2024-06-24','2024-06-24 13:30:00+00:00','2024-06-24 20:00:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (32,32,1,'2024-06-24','2024-06-24 13:30:00+00:00','2024-06-24 20:00:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (13,13,1,'2024-06-24','2024-06-24 07:00:00+00:00','2024-06-24 15:30:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (8,8,1,'2024-06-24','2024-06-24 06:00:00+00:00','2024-06-24 18:00:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (42,42,1,'2024-06-24','2024-06-24 06:00:00+00:00','2024-06-24 18:00:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (44,44,1,'2024-06-24','2024-06-24 08:00:00','2024-06-24 20:00:00',
                'Error fetching the timezone_ID',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (43,43,1,'2024-06-24','2024-06-24 08:00:00','2024-06-24 20:00:00',
                'Error fetching the timezone_ID',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (45,45,1,'2024-06-24','2024-06-24 08:00:00','2024-06-24 20:00:00',
                'Error fetching the timezone_ID',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (37,37,1,'2024-06-24','2024-06-24 07:00:00+00:00','2024-06-24 15:30:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (46,46,1,'2024-06-24','2024-06-24 09:00:00','2024-06-24 17:30:00',
                'Error fetching the timezone_ID',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (47,47,1,'2024-06-24','2024-06-24 07:00:00+00:00','2024-06-24 15:30:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (48,48,1,'2024-06-24','2024-06-24 07:00:00+00:00','2024-06-24 15:30:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (30,30,1,'2024-06-24','2024-06-24 00:00:00+00:00','2024-06-24 06:00:00+00:00',
                'Noon trading break from 11:30 to 12:30 local time',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (49,49,1,'2024-06-24','2024-06-24 03:45:00+00:00','2024-06-24 10:00:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (49,49,1,'2024-06-24','2024-06-24 03:45:00+00:00','2024-06-24 10:00:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (27,27,1,'2024-06-24','2024-06-24 01:30:00+00:00','2024-06-24 07:00:00+00:00',
                'Noon trading break from 11:30 to 13:00 local time',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (27,27,1,'2024-06-24','2024-06-24 01:30:00+00:00','2024-06-24 07:00:00+00:00',
                'Noon trading break from 11:30 to 13:00 local time',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (10,10,1,'2024-06-24','2024-06-24 01:30:00+00:00','2024-06-24 08:00:00+00:00',
                'Noon trading break from 12:00 to 13:00 local time',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (10,10,1,'2024-06-24','2024-06-24 02:00:00+00:00','2024-06-24 09:30:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (10,10,1,'2024-06-24','2024-06-24 00:30:00+00:00','2024-06-24 07:00:00+00:00',
                '-',0)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (10,10,1,'2024-06-24','2024-06-24 01:00:00+00:00','2024-06-24 09:00:00+00:00',
                '-',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (35,35,1,'2024-06-24','2024-06-24 00:00:00','2024-06-24 23:59:00',
                'This market is global',1)
INSERT INTO "dyTRADE".financial_market_session_time_log ("financial_market_session_time_ID","financial_market_session_time_financial_market_PK","financial_market_session_time_market_session_PK","financial_market_session_time_log_utc_date","financial_market_session_time_opening_UTC_time","financial_market_session_time_closure_UTC_time","financial_market_session_time_note","financial_market_session_time_activity_status")
                VALUES (35,35,1,'2024-06-24','2024-06-24 00:00:00','2024-06-24 23:59:00',
                'This market is global',1)